# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: e-commerce-events.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "e-commerce-events.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17\x65-commerce-events.proto\x12\tecommerce\x1a\x1fgoogle/protobuf/timestamp.proto"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t"Z\n\x07Product\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t"\x85\x01\n\x10ProductViewEvent\x12\x1d\n\x04user\x18\x01 \x01(\x0b\x32\x0f.ecommerce.User\x12#\n\x07product\x18\x02 \x01(\x0b\x32\x12.ecommerce.Product\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"\x82\x01\n\rPurchaseEvent\x12\x1d\n\x04user\x18\x01 \x01(\x0b\x32\x0f.ecommerce.User\x12#\n\x07product\x18\x02 \x01(\x0b\x32\x12.ecommerce.Product\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"|\n\x0e\x45\x43ommerceEvent\x12\x33\n\x0cproduct_view\x18\x01 \x01(\x0b\x32\x1b.ecommerce.ProductViewEventH\x00\x12,\n\x08purchase\x18\x02 \x01(\x0b\x32\x18.ecommerce.PurchaseEventH\x00\x42\x07\n\x05\x65ventB/\n\x1b\x63om.ortisan.ecommerce.protoB\x0e\x45\x43ommerceProtoP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "e_commerce_events_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"\n\033com.ortisan.ecommerce.protoB\016ECommerceProtoP\001"
    _globals["_USER"]._serialized_start = 71
    _globals["_USER"]._serialized_end = 118
    _globals["_PRODUCT"]._serialized_start = 120
    _globals["_PRODUCT"]._serialized_end = 210
    _globals["_PRODUCTVIEWEVENT"]._serialized_start = 213
    _globals["_PRODUCTVIEWEVENT"]._serialized_end = 346
    _globals["_PURCHASEEVENT"]._serialized_start = 349
    _globals["_PURCHASEEVENT"]._serialized_end = 479
    _globals["_ECOMMERCEEVENT"]._serialized_start = 481
    _globals["_ECOMMERCEEVENT"]._serialized_end = 605
# @@protoc_insertion_point(module_scope)
