[package]
name = "users_api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
surrealdb = "2.3.7"
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1.17.0", features = ["v4", "v7", "std"] }
regex = "1.11.1"
thiserror = "2.0.12"
